# Generated by Django 5.1.3 on 2024-11-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название поставщика', max_length=100, unique=True, verbose_name='Название')),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Уровень в сети')),
                ('debt', models.DecimalField(decimal_places=2, help_text='Укажите долг перед поставщиком', max_digits=10, verbose_name='Долг перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи в БД')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='retail.basesupplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'сетевой элемент',
                'verbose_name_plural': 'сетевые элементы',
                'ordering': ['level'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите имэйл', max_length=100, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='№ дома')),
                ('base_supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.basesupplier')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите продукт', max_length=100, verbose_name='Наименование продукта')),
                ('description', models.CharField(blank=True, help_text='Введите описание продукта', max_length=1000, null=True, verbose_name='Описание')),
                ('model', models.CharField(blank=True, help_text='Введите модель продукта', max_length=1000, null=True, verbose_name='Модель')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='retail/photo', verbose_name='Фото продукта')),
                ('price', models.IntegerField(help_text='Введите цену продукта', verbose_name='Цена')),
                ('manufactured_at', models.DateField(blank=True, help_text='Введите дату выхода продукта на рынок', null=True, verbose_name='Дата выхода продукта на рынок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.basesupplier')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'description', 'model', 'price'],
            },
        ),
    ]
